import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import 'swiper/css/pagination';
import 'swiper/css';
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import { Toaster } from "@/components/ui/sonner"
import Providers from "@/Providers";

const poppins = Poppins({
  weight: ["400","500","600","700"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-white dark:bg-stone-800`}
      >
        <Providers>
          <Navbar/>
          <main className="overflow-x-hidden mt-[68px] pt-10 min-h-page container mx-auto px-20 bg-white dark:bg-stone-800 ">
            {children}
          </main>
          <Toaster/>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
